export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const OPEN_PRODUCT = "OPEN_PRODUCT";
export const CLOSE_PRODUCT = "CLOSE_PRODUCT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_CONTACT_DATA_ERROR = "GET_CONTACT_DATA_ERROR";
export const GET_CONTACT_DATA_SUCCESS = "GET_CONTACT_DATA_SUCCESS";
export const GET_MENU_DATA_SUCCESS = "GET_MENU_DATA_SUCCESS";
export const GET_MENU_DATA_ERROR = "GET_MENU_DATA_ERROR";
//order context
export const SEND_ORDER = "SEND_ORDER";
export const CLOSE_POSITION = "CLOSE_POSITION";
export const SUME_FULL_AMOUNT = "SUME_FULL_AMOUNT";
